### ISSUE TITLE
Я бы не стал относить его к Creational

### ISSUE THREAD

**Issue by PartyZan13** [yvv4git/php_design_patterns#6]
https://github.com/yvv4git/php_design_patterns/blob/01d578cc4e5229a799b88b178fc6f84ffe55e789/src/Creational/Registry/ProductRegistry.php#L3

 а скорее к Structural. Но это не точно =)
Еще его советуют избегать - он привносит (используется как) глобальное состояние.
Ну и наверное правильнее писать не "хэшь" а "хэш-мап".

**Comment by yvv4git** [comment]
Спасибо! Поправлю...

**Comment by yvv4git** [comment]
Поправил
